// Persistence of the Customers module (schema `customers`).
using Commerce.BuildingBlocks.Persistence;
using Commerce.Modules.Customers.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Commerce.Modules.Customers.Data;

public sealed class CustomersDbContext(DbContextOptions<CustomersDbContext> options, IServiceProvider services) : ModuleDbContext(options, services)
{
    public const string SchemaName = "customers";
    public override string Schema => SchemaName;

    public DbSet<Customer> Customers => Set<Customer>();
}

internal sealed class CustomerConfiguration : IEntityTypeConfiguration<Customer>
{
    public void Configure(EntityTypeBuilder<Customer> customer)
    {
        customer.ToTable("customers");
        customer.HasKey(c => c.Id);
        customer.Property(c => c.UserSubject).HasMaxLength(64);
        customer.HasIndex(c => c.UserSubject).IsUnique();
        customer.Property(c => c.DisplayName).HasMaxLength(100);
        customer.Property(c => c.Email).HasMaxLength(254);
        customer.HasIndex(c => c.Email);
        customer.Property(c => c.Phone).HasMaxLength(30);
        customer.Property(c => c.Tier).HasConversion<string>().HasMaxLength(20);
        customer.Property(c => c.Version).IsConcurrencyToken();
        customer.OwnsMany(c => c.Addresses, address =>
        {
            address.ToTable("addresses");
            address.WithOwner().HasForeignKey("customer_id");
            // Surrogate key generated by the database so new addresses are inserted; the
            // domain id stays unique and is what the API exposes.
            address.Property<long>("row_id").ValueGeneratedOnAdd();
            address.HasKey("row_id");
            address.HasIndex(a => a.Id).IsUnique();
            address.Property(a => a.Label).HasMaxLength(40);
            address.Property(a => a.Line1).HasMaxLength(200);
            address.Property(a => a.City).HasMaxLength(100);
            address.Property(a => a.PostalCode).HasMaxLength(20);
            address.Property(a => a.Country).HasMaxLength(2);
        });
        customer.Navigation(c => c.Addresses).HasField("_addresses");
    }
}

internal sealed class CustomersDesignTimeFactory() : DesignTimeFactory<CustomersDbContext>(CustomersDbContext.SchemaName);
