// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sscp.ControlPlane.Infrastructure.Persistence;

#nullable disable

namespace Sscp.ControlPlane.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ControlPlaneDbContext))]
    [Migration("20260927183546_InitialTrustModel")]
    partial class InitialTrustModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("trust")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sscp.ControlPlane.Domain.Artifacts.Artifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Application")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("application");

                    b.Property<Guid>("BuildId")
                        .HasColumnType("uuid")
                        .HasColumnName("build_id");

                    b.Property<string>("CandidateRepository")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("candidate_repository");

                    b.Property<string>("Commit")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("commit");

                    b.Property<string>("Deployable")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("deployable");

                    b.Property<string>("Digest")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("character varying(71)")
                        .HasColumnName("digest");

                    b.Property<Guid?>("LatestDecisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("latest_decision_id");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("state");

                    b.Property<string>("TrustedRepository")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("trusted_repository");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_artifacts");

                    b.HasIndex("Digest")
                        .HasDatabaseName("ix_artifacts_digest");

                    b.HasIndex("BuildId", "Deployable")
                        .IsUnique()
                        .HasDatabaseName("ix_artifacts_build_id_deployable");

                    b.ToTable("artifacts", "trust");
                });

            modelBuilder.Entity("Sscp.ControlPlane.Domain.Auditing.AuditEntry", b =>
                {
                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Sequence"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("actor");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PreviousHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("previous_hash");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("subject_type");

                    b.HasKey("Sequence")
                        .HasName("pk_audit_log");

                    b.HasIndex("SubjectType", "SubjectId")
                        .HasDatabaseName("ix_audit_log_subject_type_subject_id");

                    b.ToTable("audit_log", "trust");
                });

            modelBuilder.Entity("Sscp.ControlPlane.Domain.Builds.Build", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Application")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("application");

                    b.Property<string>("Commit")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("commit");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<int?>("PullRequest")
                        .HasColumnType("integer")
                        .HasColumnName("pull_request");

                    b.Property<string>("Ref")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ref");

                    b.Property<string>("SourceRepository")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_repository");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.PrimitiveCollection<List<long>>("_runIds")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("pipeline_run_ids");

                    b.HasKey("Id")
                        .HasName("pk_builds");

                    b.HasIndex("Application", "Commit", "Kind")
                        .HasDatabaseName("ix_builds_application_commit_kind");

                    b.ToTable("builds", "trust");
                });

            modelBuilder.Entity("Sscp.ControlPlane.Domain.Evidence.EvidenceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Application")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("application");

                    b.Property<string>("ArtifactDigest")
                        .HasMaxLength(71)
                        .HasColumnType("character varying(71)")
                        .HasColumnName("artifact_digest");

                    b.Property<Guid>("BuildId")
                        .HasColumnType("uuid")
                        .HasColumnName("build_id");

                    b.Property<string>("Commit")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("commit");

                    b.Property<string>("Deployable")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("deployable");

                    b.Property<string>("Execution")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("execution");

                    b.Property<string>("ExecutionError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("execution_error");

                    b.Property<string>("GateDetail")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("gate_detail");

                    b.Property<bool?>("GatePassed")
                        .HasColumnType("boolean")
                        .HasColumnName("gate_passed");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("job_name");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("kind");

                    b.Property<long>("PipelineRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("pipeline_run_id");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("SubmittedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("submitted_by");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Report", "Sscp.ControlPlane.Domain.Evidence.EvidenceRecord.Report#RawReport", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("report_content_type");

                            b1.Property<string>("ObjectKey")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("report_object_key");

                            b1.Property<string>("Sha256")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("report_sha256");

                            b1.Property<long>("SizeBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("report_size_bytes");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Tool", "Sscp.ControlPlane.Domain.Evidence.EvidenceRecord.Tool#ToolInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset?>("DatabaseUpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("tool_database_updated_at");

                            b1.Property<string>("DatabaseVersion")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("tool_database_version");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("tool_name");

                            b1.Property<string>("Version")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("tool_version");
                        });

                    b.HasKey("Id")
                        .HasName("pk_evidence");

                    b.HasIndex("BuildId")
                        .HasDatabaseName("ix_evidence_build_id");

                    b.HasIndex("Application", "Kind")
                        .HasDatabaseName("ix_evidence_application_kind");

                    b.ToTable("evidence", "trust");
                });

            modelBuilder.Entity("Sscp.ControlPlane.Domain.Evidence.Finding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EvidenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("evidence_id");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("fingerprint");

                    b.Property<bool>("FixAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("fix_available");

                    b.Property<string>("FixedVersion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("fixed_version");

                    b.Property<string>("InstalledVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("installed_version");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("location");

                    b.Property<string>("Package")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("package");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("rule_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_findings");

                    b.HasIndex("EvidenceId")
                        .HasDatabaseName("ix_findings_evidence_id");

                    b.HasIndex("Fingerprint")
                        .HasDatabaseName("ix_findings_fingerprint");

                    b.ToTable("findings", "trust");
                });

            modelBuilder.Entity("Sscp.ControlPlane.Domain.Exceptions.RiskException", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Application")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("application");

                    b.Property<string>("Approver")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("approver");

                    b.Property<string>("CompensatingControls")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("compensating_controls");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<string>("DecisionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("decision_note");

                    b.Property<string>("Deployable")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("deployable");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("FindingFingerprint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("finding_fingerprint");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("justification");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("kind");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("owner");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_risk_exceptions");

                    b.HasIndex("Application", "Status")
                        .HasDatabaseName("ix_risk_exceptions_application_status");

                    b.ToTable("risk_exceptions", "trust");
                });

            modelBuilder.Entity("Sscp.ControlPlane.Domain.Records.DeploymentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Application")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("application");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("environment");

                    b.Property<string>("GitOpsRevision")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("git_ops_revision");

                    b.Property<string>("HealthStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("health_status");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("images");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<Guid?>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("sync_status");

                    b.HasKey("Id")
                        .HasName("pk_deployments");

                    b.HasIndex("ReleaseId")
                        .HasDatabaseName("ix_deployments_release_id");

                    b.ToTable("deployments", "trust");
                });

            modelBuilder.Entity("Sscp.ControlPlane.Domain.Records.PromotionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid")
                        .HasColumnName("artifact_id");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("from");

                    b.Property<long>("PipelineRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("pipeline_run_id");

                    b.Property<DateTimeOffset>("PromotedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("promoted_at");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("to");

                    b.HasKey("Id")
                        .HasName("pk_promotions");

                    b.HasIndex("ArtifactId")
                        .HasDatabaseName("ix_promotions_artifact_id");

                    b.ToTable("promotions", "trust");
                });

            modelBuilder.Entity("Sscp.ControlPlane.Domain.Records.SignatureRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid")
                        .HasColumnName("artifact_id");

                    b.Property<string>("AttestationReferences")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("attestation_references");

                    b.Property<string>("Digest")
                        .IsRequired()
                        .HasMaxLength(71)
                        .HasColumnType("character varying(71)")
                        .HasColumnName("digest");

                    b.Property<string>("KeyReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key_reference");

                    b.Property<long>("PipelineRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("pipeline_run_id");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.Property<string>("SignatureReference")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("signature_reference");

                    b.Property<DateTimeOffset>("SignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("signed_at");

                    b.HasKey("Id")
                        .HasName("pk_signatures");

                    b.HasIndex("ArtifactId")
                        .HasDatabaseName("ix_signatures_artifact_id");

                    b.ToTable("signatures", "trust");
                });

            modelBuilder.Entity("Sscp.ControlPlane.Domain.Records.TrustDecisionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppliedExceptions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("applied_exceptions");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid")
                        .HasColumnName("artifact_id");

                    b.Property<DateTimeOffset>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evaluated_at");

                    b.Property<string>("EvaluatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("evaluated_by");

                    b.Property<string>("EvidenceUsed")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("evidence_used");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("outcome");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("policy_version");

                    b.Property<Guid?>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.Property<string>("Results")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("results");

                    b.HasKey("Id")
                        .HasName("pk_trust_decisions");

                    b.HasIndex("ArtifactId")
                        .HasDatabaseName("ix_trust_decisions_artifact_id");

                    b.ToTable("trust_decisions", "trust");
                });

            modelBuilder.Entity("Sscp.ControlPlane.Domain.Releases.Release", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Application")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("application");

                    b.Property<Guid>("BuildId")
                        .HasColumnType("uuid")
                        .HasColumnName("build_id");

                    b.Property<string>("Commit")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("commit");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("GitOpsCommit")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("git_ops_commit");

                    b.Property<long?>("PipelineRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("pipeline_run_id");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("requested_by");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("state");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tag");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.PrimitiveCollection<List<Guid>>("_artifactIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("artifact_ids");

                    b.HasKey("Id")
                        .HasName("pk_releases");

                    b.HasIndex("Application", "Tag")
                        .IsUnique()
                        .HasDatabaseName("ix_releases_application_tag");

                    b.ToTable("releases", "trust");
                });

            modelBuilder.Entity("Sscp.ControlPlane.Domain.Evidence.Finding", b =>
                {
                    b.HasOne("Sscp.ControlPlane.Domain.Evidence.EvidenceRecord", null)
                        .WithMany("Findings")
                        .HasForeignKey("EvidenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_findings_evidence_evidence_id");
                });

            modelBuilder.Entity("Sscp.ControlPlane.Domain.Evidence.EvidenceRecord", b =>
                {
                    b.Navigation("Findings");
                });
#pragma warning restore 612, 618
        }
    }
}
