// Persistence of the Payments module (schema `payments`).
using Commerce.BuildingBlocks.Persistence;
using Commerce.Modules.Payments.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Commerce.Modules.Payments.Data;

public sealed class PaymentsDbContext(DbContextOptions<PaymentsDbContext> options, IServiceProvider services) : ModuleDbContext(options, services)
{
    public const string SchemaName = "payments";
    public override string Schema => SchemaName;

    public DbSet<Payment> Payments => Set<Payment>();
}

internal sealed class PaymentConfiguration : IEntityTypeConfiguration<Payment>
{
    public void Configure(EntityTypeBuilder<Payment> payment)
    {
        payment.ToTable("payments");
        payment.HasKey(p => p.Id);
        // One payment per order also makes the capture handler idempotent at database level.
        payment.HasIndex(p => p.OrderId).IsUnique();
        payment.Property(p => p.Amount).HasPrecision(12, 2);
        payment.Property(p => p.Currency).HasMaxLength(3);
        payment.Property(p => p.Method).HasMaxLength(10);
        payment.Property(p => p.Status).HasConversion<string>().HasMaxLength(20);
        payment.Property(p => p.ProviderReference).HasMaxLength(64);
        payment.Property(p => p.FailureReason).HasMaxLength(200);
        payment.Property(p => p.TokenFingerprint).HasMaxLength(12);
        payment.Property(p => p.Version).IsConcurrencyToken();
        payment.Ignore(p => p.RefundedAmount);
        payment.Ignore(p => p.RefundableAmount);
        payment.OwnsMany(p => p.Refunds, refund =>
        {
            refund.ToTable("refunds");
            refund.WithOwner().HasForeignKey("payment_id");
            // Surrogate key generated by the database so new refunds are inserted.
            refund.Property<long>("row_id").ValueGeneratedOnAdd();
            refund.HasKey("row_id");
            refund.HasIndex(r => r.Id).IsUnique();
            refund.Property(r => r.Amount).HasPrecision(12, 2);
            refund.Property(r => r.Reason).HasMaxLength(200);
            refund.Property(r => r.RequestedBy).HasMaxLength(100);
        });
        payment.Navigation(p => p.Refunds).HasField("_refunds");
    }
}

internal sealed class PaymentsDesignTimeFactory() : DesignTimeFactory<PaymentsDbContext>(PaymentsDbContext.SchemaName);
