<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="../../BuildingBlocks/Commerce.BuildingBlocks/Commerce.BuildingBlocks.csproj" />
    <ProjectReference Include="../../Modules/Documents/Commerce.Modules.Documents.Contracts/Commerce.Modules.Documents.Contracts.csproj" />
    <ProjectReference Include="../../Modules/Orders/Commerce.Modules.Orders.Contracts/Commerce.Modules.Orders.Contracts.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
  </ItemGroup>
</Project>
