"""Docker Compose invocation for the platform services.

The Compose file never contains versions or credentials. This module generates the env
file that supplies them: image references come from versions.yaml and credentials from
the local credential store, so both have a single source of truth.
"""
from __future__ import annotations

from pathlib import Path

from sscp import credentials, paths, shell, versions

PROJECT = "sscp"
COMPOSE_FILE = paths.PLATFORM_DIR / "compose.yaml"
ENV_FILE = paths.GENERATED_DIR / "compose.env"

IMAGE_VARIABLES = {
    "IMAGE_POSTGRES": "postgres",
    "IMAGE_VAULT": "vault",
    "IMAGE_KEYCLOAK": "keycloak",
    "IMAGE_MINIO": "minio",
    "IMAGE_GITEA": "gitea",
    "IMAGE_SONARQUBE": "sonarqube",
    "IMAGE_REDIS": "redis",
    "IMAGE_RABBITMQ": "rabbitmq",
    "IMAGE_GITEA_RUNNER": "giteaRunner",
    "IMAGE_DOTNET_SDK": "dotnetSdk",
    "IMAGE_DOTNET_ASPNET": "dotnetAspnet",
}

# Credential variables and the credential-store key each one comes from.
CREDENTIAL_VARIABLES = {
    "POSTGRES_ADMIN_PASSWORD": "postgres.admin",
    "GITEA_DB_PASSWORD": "postgres.gitea",
    "KEYCLOAK_DB_PASSWORD": "postgres.keycloak",
    "SONARQUBE_DB_PASSWORD": "postgres.sonarqube",
    "CONTROLPLANE_DB_PASSWORD": "postgres.controlplane",
    "CONTROLPLANE_APP_DB_PASSWORD": "postgres.controlplane-app",
    "MINIO_CONTROLPLANE_SECRET": "minio.controlplane",
    "MINIO_ROOT_PASSWORD": "minio.root",
    "KEYCLOAK_ADMIN_PASSWORD": "keycloak.bootstrap-admin",
    "GITEA_METRICS_TOKEN": "gitea.metrics-token",
    "COMMERCE_DEV_POSTGRES_PASSWORD": "workload-dev.postgres",
    "REDIS_DEV_PASSWORD": "workload-dev.redis",
    "RABBITMQ_DEV_PASSWORD": "workload-dev.rabbitmq",
    "COMMERCE_DEV_MINIO_PASSWORD": "workload-dev.minio",
    "CONTROLPLANE_WEBHOOK_SECRET": "controlplane.webhook-secret",
}

LATER_CREDENTIAL_VARIABLES = {
    "CONTROLPLANE_GITEA_TOKEN": "gitea.token.sscp-controlplane",
    "CONTROLPLANE_VAULT_ROLE_ID": "vault.approle.controlplane.role-id",
    "CONTROLPLANE_VAULT_SECRET_ID": "vault.approle.controlplane.secret-id",
    "CONTROLPLANE_ARGOCD_TOKEN": "argocd.notifications-token",
}


def _posix(path: Path) -> str:
    return path.resolve().as_posix()


def write_env_file() -> Path:
    lines = [
        "# Generated by `sscp up` from versions.yaml and .local/secrets. Do not edit or commit.",
        f"PKI_DIR={_posix(paths.PKI_DIR)}",
        f"PLATFORM_DIR={_posix(paths.PLATFORM_DIR)}",
        f"GENERATED_DIR={_posix(paths.GENERATED_DIR)}",
        f"MINIO_ROOT_USER={credentials.get('minio.root-user', lambda: 'sscp-minio-admin')}",
        f"GITEA_SECRET_KEY={credentials.get('gitea.secret-key', lambda: credentials.password(64))}",
        f"GITEA_INTERNAL_TOKEN={credentials.get('gitea.internal-token', lambda: credentials.password(64))}",
    ]
    lines += [f"{variable}={versions.image(name)}" for variable, name in IMAGE_VARIABLES.items()]
    lines += [f"{variable}={credentials.get(key)}" for variable, key in CREDENTIAL_VARIABLES.items()]
    # Values created by later bootstrap steps (for example Gitea API tokens) are empty
    # until those steps have run; `sscp up` rewrites this file before the services that
    # need them start.
    lines += [f"{variable}={credentials.find(key) or ''}" for variable, key in LATER_CREDENTIAL_VARIABLES.items()]
    paths.GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    ENV_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    return ENV_FILE


def compose(*args: str, profiles: list[str] | None = None, check: bool = True, timeout: float | None = None,
            env: dict[str, str] | None = None):
    command = ["docker", "compose", "-p", PROJECT, "-f", str(COMPOSE_FILE), "--env-file", str(ENV_FILE)]
    for profile in profiles or []:
        command += ["--profile", profile]
    return shell.run([*command, *args], check=check, timeout=timeout, env=env)
