// Persistence of the Catalog module (schema `catalog`).
using Commerce.BuildingBlocks.Persistence;
using Commerce.Modules.Catalog.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Commerce.Modules.Catalog.Data;

public sealed class CatalogDbContext(DbContextOptions<CatalogDbContext> options, IServiceProvider services) : ModuleDbContext(options, services)
{
    public const string SchemaName = "catalog";
    public override string Schema => SchemaName;

    public DbSet<Product> Products => Set<Product>();
}

internal sealed class ProductConfiguration : IEntityTypeConfiguration<Product>
{
    public void Configure(EntityTypeBuilder<Product> product)
    {
        product.ToTable("products");
        product.HasKey(p => p.Id);
        product.Property(p => p.Sku).HasMaxLength(12);
        product.HasIndex(p => p.Sku).IsUnique();
        product.Property(p => p.Name).HasMaxLength(Product.MaxNameLength);
        product.Property(p => p.Description).HasMaxLength(2000);
        product.Property(p => p.Category).HasMaxLength(60);
        product.Property(p => p.Status).HasConversion<string>().HasMaxLength(20);
        product.ComplexProperty(p => p.Price, price =>
        {
            price.Property(m => m.Amount).HasColumnName("price").HasPrecision(12, 2);
            price.Property(m => m.Currency).HasColumnName("currency").HasMaxLength(3);
        });
        product.Property(p => p.Version).IsConcurrencyToken();
        product.OwnsMany(p => p.PriceHistory, history =>
        {
            history.ToTable("price_history");
            history.WithOwner().HasForeignKey("product_id");
            // Surrogate key generated by the database so new history rows are inserted.
            history.Property<long>("row_id").ValueGeneratedOnAdd();
            history.HasKey("row_id");
            history.HasIndex(h => h.Id).IsUnique();
            history.Property(h => h.OldPrice).HasPrecision(12, 2);
            history.Property(h => h.NewPrice).HasPrecision(12, 2);
            history.Property(h => h.ChangedBy).HasMaxLength(100);
        });
        product.Navigation(p => p.PriceHistory).HasField("_priceHistory");
    }
}

internal sealed class CatalogDesignTimeFactory() : DesignTimeFactory<CatalogDbContext>(CatalogDbContext.SchemaName);
